/**
 * Generate valid DevisPro license keys.
 *
 * Usage:
 *   node scripts/generate-license.mjs        → generates 1 key
 *   node scripts/generate-license.mjs 5      → generates 5 keys
 *   node scripts/generate-license.mjs 10     → generates 10 keys
 *
 * Key format: XXXX-XXXX-XXXX-XXXX
 *   - Groups 1-3: random alphanumeric
 *   - Group 4: HMAC-SHA256 checksum of groups 1-3
 *
 * Only keys generated by this script will be accepted by the app.
 * Keep this script SECRET — do NOT share it or include it in releases.
 */

import { createHmac, randomBytes } from 'crypto'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

// Load secret from .env file (not in source code!)
const __dirname = dirname(fileURLToPath(import.meta.url))
const envPath = resolve(__dirname, '..', '.env')
const envContent = readFileSync(envPath, 'utf8')
const match = envContent.match(/LICENSE_KEY_SECRET=(.+)/)
const LICENSE_KEY_SECRET = match ? match[1].trim() : ''

if (!LICENSE_KEY_SECRET) {
  console.error('❌ LICENSE_KEY_SECRET introuvable dans .env !')
  process.exit(1)
}
const VALID_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

function randomGroup() {
  const bytes = randomBytes(4)
  return Array.from(bytes)
    .map((b) => VALID_CHARS[b % 36])
    .join('')
}

function computeChecksum(payload) {
  const hmac = createHmac('sha256', LICENSE_KEY_SECRET).update(payload).digest()
  return Array.from(hmac.slice(0, 4))
    .map((b) => VALID_CHARS[b % 36])
    .join('')
}

function generateKey() {
  const payload = `${randomGroup()}-${randomGroup()}-${randomGroup()}`
  const check = computeChecksum(payload)
  return `${payload}-${check}`
}

// --- Main ---

const count = parseInt(process.argv[2]) || 1

console.log('')
console.log(`🔑 Génération de ${count} clé(s) de licence DevisPro:`)
console.log('')

for (let i = 0; i < count; i++) {
  console.log(`  ${generateKey()}`)
}

console.log('')
console.log('💡 Donnez une clé unique à chaque client.')
console.log('   Elle sera liée à sa machine lors de l\'activation.')
console.log('')
